# Generated by Django 5.2.7 on 2026-04-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='shape_data',
            field=models.JSONField(blank=True, default=list, help_text='List of shape dicts rendered as SVG canvas'),
        ),
    ]
