# Generated by Django 5.2.7 on 2026-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_probleminteraction_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminteraction',
            name='error_type',
            field=models.CharField(blank=True, default='', help_text='Misconception category for wrong answers', max_length=60),
        ),
    ]
