# Generated by Django 5.2.7 on 2026-04-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_add_parent_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_en',
            field=models.TextField(blank=True, help_text='Step-by-step worked solution (English). One step per line.'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation_fr',
            field=models.TextField(blank=True, help_text='Step-by-step worked solution (French). One step per line.'),
        ),
    ]
