# Generated by Django 5.1.4 on 2026-09-13 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_add_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('icon', models.CharField(default='🧩', max_length=8)),
                ('grade', models.PositiveSmallIntegerField(blank=True, help_text='School grade (3, 5…). Blank = general / any grade.', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Stable id; matches the generator key for code-backed skills.', max_length=60, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_fr', models.CharField(blank=True, max_length=120)),
                ('description_en', models.TextField(blank=True, help_text='What the exercise looks like to a child. Used by AI search & classification.')),
                ('description_fr', models.TextField(blank=True)),
                ('keywords_en', models.TextField(blank=True, help_text='Comma-separated phrases a kid or parent might use to describe this skill.')),
                ('keywords_fr', models.TextField(blank=True)),
                ('curriculum_ref', models.CharField(blank=True, help_text='e.g. PFEQ section / progression code', max_length=120)),
                ('answer_type', models.CharField(blank=True, choices=[('integer', 'Integer'), ('decimal', 'Decimal number'), ('fraction', 'Fraction'), ('money', 'Money amount'), ('duration', 'Duration (h / min)'), ('coordinate', 'Coordinate pair (x, y)'), ('symbol', 'Comparison symbol (<, >, =)'), ('text', 'Free text / word')], help_text='Default typed-answer format. Blank = infer from the problem.', max_length=20)),
                ('generator_slug', models.CharField(blank=True, help_text='Key in quiz.generators.GENERATORS for code-backed skills.', max_length=60)),
                ('level_sequence', models.JSONField(blank=True, default=list, help_text="e.g. ['easy', 'medium', 'hard']")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('downgrade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.skill')),
                ('mastery_next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.skill')),
                ('next_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.skill')),
                ('prereq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='quiz.skill')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='quiz.skilldomain')),
            ],
            options={
                'ordering': ['domain__order', 'order', 'id'],
            },
        ),
    ]
