# Generated by Django 5.1.4 on 2026-09-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_seed_grade6_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='School grade the child is in; the home page opens on it by default.', null=True),
        ),
    ]
