# Generated by Django 5.1.4 on 2026-09-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_resolution_level_g35'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parentassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='parentassignment',
            name='correct_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentassignment',
            name='goal',
            field=models.PositiveSmallIntegerField(default=10, help_text='Questions the child must answer for the assignment to count as done'),
        ),
        migrations.AddField(
            model_name='parentassignment',
            name='questions_done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentassignment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentassignment',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
