# Generated by Django 5.1.4 on 2026-09-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_seed_clock_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, help_text='When the parent clicked the confirmation link sent to user.email', null=True),
        ),
    ]
